# Generated by Django 2.1.3 on 2019-07-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryaccess',
            name='library',
        ),
        migrations.RemoveField(
            model_name='libraryaccess',
            name='users',
        ),
        migrations.DeleteModel(
            name='LibraryAccess',
        ),
    ]
