# Generated by Django 2.1.3 on 2019-07-31 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_accounts', '0002_auto_20190731_1011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agreement',
        ),
        migrations.RemoveField(
            model_name='secretcode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useragree',
            name='user',
        ),
        migrations.DeleteModel(
            name='SecretCode',
        ),
        migrations.DeleteModel(
            name='UserAgree',
        ),
    ]
