# Generated by Django 2.1.3 on 2018-12-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2_notebooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1_accounts.Library'),
        ),
    ]
