# Generated by Django 2.1.3 on 2018-12-23 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2_notebooks', '0003_auto_20181218_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='list',
            new_name='is_list',
        ),
        migrations.RemoveField(
            model_name='note',
            name='note',
        ),
        migrations.RemoveField(
            model_name='note',
            name='paper',
        ),
        migrations.AddField(
            model_name='note',
            name='is_note',
            field=models.BooleanField(default=False, verbose_name='Is note'),
        ),
        migrations.AddField(
            model_name='note',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note', to='app2_notebooks.Notebook'),
        ),
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='text without format'),
        ),
    ]
