# Generated by Django 2.1.3 on 2018-12-23 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2_notebooks', '0004_auto_20181223_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='ck_text',
        ),
    ]
