# Generated by Django 2.1.3 on 2018-12-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_notebooks', '0006_auto_20181223_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_list',
            field=models.BooleanField(default=False, verbose_name='is_list'),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_note',
            field=models.BooleanField(default=False, verbose_name='is_note'),
        ),
    ]
