# Generated by Django 2.1.3 on 2018-12-28 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_notebooks', '0008_auto_20181228_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app2_notebooks.Note'),
        ),
    ]
