# Generated by Django 2.1.3 on 2019-01-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_notebooks', '0009_auto_20181228_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['-active', '-title', 'note', 'ordering_number'], 'verbose_name': 'Point', 'verbose_name_plural': '1.1.2 Point'},
        ),
        migrations.AddField(
            model_name='point',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
    ]
