# Generated by Django 2.1.3 on 2019-02-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_notebooks', '0010_auto_20190114_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['user_id', 'note', 'ordering_number', 'id', 'title'], 'verbose_name': 'Point', 'verbose_name_plural': '1.1.2 Point'},
        ),
        migrations.RemoveField(
            model_name='point',
            name='active',
        ),
        migrations.AddField(
            model_name='point',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AddField(
            model_name='point',
            name='is_crossed',
            field=models.BooleanField(default=True, verbose_name='is_crossed out'),
        ),
    ]
