# Generated by Django 2.1.3 on 2019-03-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_notebooks', '0011_auto_20190225_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
        migrations.AlterField(
            model_name='point',
            name='is_crossed',
            field=models.BooleanField(default=False, verbose_name='is_crossed out'),
        ),
    ]
