# Generated by Django 2.1.3 on 2019-04-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2_notebooks', '0012_auto_20190326_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='sub_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2_notebooks.Point'),
        ),
    ]
