# Generated by Django 2.1.3 on 2019-04-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2_notebooks', '0014_auto_20190427_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='parent_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_points', to='app2_notebooks.Point'),
        ),
    ]
