# Generated by Django 2.1.3 on 2019-07-31 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2_notebooks', '0015_auto_20190430_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['user_id', 'note', 'is_crossed', 'ordering_number', 'title', 'id'], 'verbose_name': 'Point', 'verbose_name_plural': '1.1.2 Point'},
        ),
    ]
