# Generated by Django 2.1.3 on 2019-07-31 11:10

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('app2_notebooks', '0016_auto_20190731_0946'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table=None,
        ),
        migrations.AlterModelTable(
            name='notebook',
            table=None,
        ),
        migrations.AlterModelTable(
            name='point',
            table=None,
        ),
    ]
